"""add valuation_notes to vehicles

Revision ID: 2665375ffb1a
Revises: cdec83975af0
Create Date: 2026-03-22 19:22:16.653307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2665375ffb1a'
down_revision: Union[str, Sequence[str], None] = 'cdec83975af0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('context', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('raw_ai_response', sa.Text(), nullable=True),
    sa.Column('parsed_findings', sa.Text(), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('missing_fields', sa.Text(), nullable=True),
    sa.Column('proposed_changes', sa.Text(), nullable=True),
    sa.Column('accepted_change_ids', sa.Text(), nullable=True),
    sa.Column('chat_messages', sa.Text(), nullable=True),
    sa.Column('changes_applied', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plaid_links',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('institution_id', sa.String(), nullable=True),
    sa.Column('cursor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id')
    )
    op.create_table('retirement_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('total_balance', sa.Numeric(), nullable=True),
    sa.Column('vested_balance', sa.Numeric(), nullable=True),
    sa.Column('roth_balance', sa.Numeric(), nullable=True),
    sa.Column('pretax_balance', sa.Numeric(), nullable=True),
    sa.Column('employer_match_balance', sa.Numeric(), nullable=True),
    sa.Column('other_balance', sa.Numeric(), nullable=True),
    sa.Column('pretax_deferral_rate', sa.Numeric(), nullable=True),
    sa.Column('roth_deferral_rate', sa.Numeric(), nullable=True),
    sa.Column('total_employee_contributions', sa.Numeric(), nullable=True),
    sa.Column('total_employer_contributions', sa.Numeric(), nullable=True),
    sa.Column('roth_basis', sa.Numeric(), nullable=True),
    sa.Column('account_return', sa.Numeric(), nullable=True),
    sa.Column('return_period_start', sa.Date(), nullable=True),
    sa.Column('statement_start', sa.Date(), nullable=True),
    sa.Column('statement_end', sa.Date(), nullable=True),
    sa.Column('estimated_monthly_income', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retirement_holdings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retirement_account_id', sa.Integer(), nullable=False),
    sa.Column('fund_name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=True),
    sa.Column('balance', sa.Numeric(), nullable=True),
    sa.Column('allocation_pct', sa.Numeric(), nullable=True),
    sa.Column('gain_loss', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('retirement_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('retirement_account_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(), nullable=False),
    sa.Column('roth_balance', sa.Numeric(), nullable=True),
    sa.Column('pretax_balance', sa.Numeric(), nullable=True),
    sa.Column('employer_balance', sa.Numeric(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('trim', sa.String(), nullable=True),
    sa.Column('vin', sa.String(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('condition', sa.String(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('estimated_value', sa.Numeric(), nullable=True),
    sa.Column('value_last_updated', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('valuation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_value_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_projected', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mortgages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('escrow', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('property_address', sa.String(), nullable=True))

    with op.batch_alter_table('rsu_grants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(), nullable=True))

    # Skip users.status ALTER — the users table is created by Base.metadata.create_all()
    # at app startup (not by Alembic), so it already has the correct schema.
    # On fresh installs, this table doesn't exist yet when migrations run.

    with op.batch_alter_table('vest_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vest_period', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fmv_at_vest', sa.Numeric(), nullable=True))
        batch_op.add_column(sa.Column('shares_withheld', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('shares_released', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('total_taxes_paid', sa.Numeric(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vest_events', schema=None) as batch_op:
        batch_op.drop_column('total_taxes_paid')
        batch_op.drop_column('shares_released')
        batch_op.drop_column('shares_withheld')
        batch_op.drop_column('fmv_at_vest')
        batch_op.drop_column('vest_period')

    # users.status ALTER skipped — see upgrade() comment

    with op.batch_alter_table('rsu_grants', schema=None) as batch_op:
        batch_op.drop_column('symbol')

    with op.batch_alter_table('mortgages', schema=None) as batch_op:
        batch_op.drop_column('property_address')
        batch_op.drop_column('escrow')

    op.drop_table('asset_value_histories')
    op.drop_table('vehicles')
    op.drop_table('retirement_snapshots')
    op.drop_table('retirement_holdings')
    op.drop_table('retirement_accounts')
    op.drop_table('plaid_links')
    op.drop_table('import_sessions')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
