"""initial schema - 16 tables

Revision ID: cdec83975af0
Revises: 
Create Date: 2026-03-13 15:44:57.804632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdec83975af0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('institution', sa.String(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=False),
    sa.Column('display_group', sa.String(), nullable=False),
    sa.Column('include_in_nw', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('opened_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('actual_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('cash', sa.Numeric(), nullable=True),
    sa.Column('investments', sa.Numeric(), nullable=True),
    sa.Column('company_stock', sa.Numeric(), nullable=True),
    sa.Column('home_equity', sa.Numeric(), nullable=True),
    sa.Column('retirement_bal', sa.Numeric(), nullable=True),
    sa.Column('net_worth', sa.Numeric(), nullable=True),
    sa.Column('salary_ytd', sa.Numeric(), nullable=True),
    sa.Column('rsu_income_ytd', sa.Numeric(), nullable=True),
    sa.Column('total_comp_ytd', sa.Numeric(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contribution_configs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('employee_rate', sa.Numeric(), nullable=True),
    sa.Column('employer_match', sa.Numeric(), nullable=True),
    sa.Column('annual_irs_limit', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forecasts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Numeric(), nullable=True),
    sa.Column('investments', sa.Numeric(), nullable=True),
    sa.Column('company_stock', sa.Numeric(), nullable=True),
    sa.Column('home_equity', sa.Numeric(), nullable=True),
    sa.Column('retirement_bal', sa.Numeric(), nullable=True),
    sa.Column('net_worth', sa.Numeric(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('generated_at', 'year')
    )
    op.create_table('import_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('capture_mode', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('records_created', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('parsed_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rsu_grants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('grant_date', sa.Date(), nullable=True),
    sa.Column('total_shares', sa.Integer(), nullable=True),
    sa.Column('vested_shares', sa.Integer(), nullable=True),
    sa.Column('unvested_shares', sa.Integer(), nullable=True),
    sa.Column('sellable_shares', sa.Integer(), nullable=True),
    sa.Column('share_price', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_prices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'price_date')
    )
    op.create_table('w2_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tax_year', sa.Integer(), nullable=False),
    sa.Column('gross_pay', sa.Numeric(), nullable=True),
    sa.Column('w2_wages', sa.Numeric(), nullable=True),
    sa.Column('federal_tax', sa.Numeric(), nullable=True),
    sa.Column('state_tax', sa.Numeric(), nullable=True),
    sa.Column('social_security', sa.Numeric(), nullable=True),
    sa.Column('medicare', sa.Numeric(), nullable=True),
    sa.Column('pretax_401k', sa.Numeric(), nullable=True),
    sa.Column('roth_401k', sa.Numeric(), nullable=True),
    sa.Column('cafeteria_125', sa.Numeric(), nullable=True),
    sa.Column('transit', sa.Numeric(), nullable=True),
    sa.Column('employer_health', sa.Numeric(), nullable=True),
    sa.Column('base_salary', sa.Numeric(), nullable=True),
    sa.Column('rsu_income', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tax_year')
    )
    op.create_table('balance_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'snapshot_date', 'source')
    )
    with op.batch_alter_table('balance_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_balance_account_date', ['account_id', 'snapshot_date'], unique=False)

    op.create_table('mortgages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('rate', sa.Numeric(), nullable=False),
    sa.Column('monthly_payment', sa.Numeric(), nullable=False),
    sa.Column('origination_date', sa.Date(), nullable=True),
    sa.Column('original_amount', sa.Numeric(), nullable=True),
    sa.Column('original_payoff_date', sa.Date(), nullable=True),
    sa.Column('current_balance', sa.Numeric(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_assumptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sensitivity', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'key')
    )
    op.create_table('plan_projections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(), nullable=False),
    sa.Column('salary', sa.Numeric(), nullable=True),
    sa.Column('rsu_income', sa.Numeric(), nullable=True),
    sa.Column('total_comp', sa.Numeric(), nullable=True),
    sa.Column('cash', sa.Numeric(), nullable=True),
    sa.Column('investments', sa.Numeric(), nullable=True),
    sa.Column('company_stock', sa.Numeric(), nullable=True),
    sa.Column('home_equity', sa.Numeric(), nullable=True),
    sa.Column('retirement_bal', sa.Numeric(), nullable=True),
    sa.Column('net_worth', sa.Numeric(), nullable=True),
    sa.Column('withdrawal', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plan_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'year')
    )
    op.create_table('property_valuations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(), nullable=False),
    sa.Column('valuation_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('account_id', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=True),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('category_group', sa.String(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transaction_category_date', ['category', 'date'], unique=False)
        batch_op.create_index('ix_transaction_date', ['date'], unique=False)

    op.create_table('vest_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('grant_id', sa.String(), nullable=False),
    sa.Column('vest_date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('vest_price', sa.Numeric(), nullable=True),
    sa.Column('is_actual', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['grant_id'], ['rsu_grants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vest_events')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transaction_date')
        batch_op.drop_index('ix_transaction_category_date')

    op.drop_table('transactions')
    op.drop_table('property_valuations')
    op.drop_table('plan_projections')
    op.drop_table('plan_assumptions')
    op.drop_table('mortgages')
    with op.batch_alter_table('balance_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_balance_account_date')

    op.drop_table('balance_snapshots')
    op.drop_table('w2_records')
    op.drop_table('stock_prices')
    op.drop_table('rsu_grants')
    op.drop_table('plan_versions')
    op.drop_table('import_logs')
    op.drop_table('forecasts')
    op.drop_table('contribution_configs')
    op.drop_table('actual_snapshots')
    op.drop_table('accounts')
    # ### end Alembic commands ###
