#!/usr/bin/env bash
# setup-runner.sh — Bootstrap a Claude Code runner environment for Tallied
# Called automatically via the SessionStart hook in .claude/settings.json
set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_ROOT"

# ── Colors ───────────────────────────────────────────────────────────────────
green()  { printf '\033[0;32m%s\033[0m\n' "$*"; }
yellow() { printf '\033[0;33m%s\033[0m\n' "$*"; }
red()    { printf '\033[0;31m%s\033[0m\n' "$*"; }

# ── 1. Backend .env ─────────────────────────────────────────────────────────
if [ ! -f backend/.env ]; then
  yellow "[setup] Creating backend/.env from template..."
  SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_urlsafe(64))")
  cat > backend/.env <<EOF
# Auto-generated by scripts/setup-runner.sh
FINANCE_DATABASE_URL=postgresql://tallied:tallied_dev@localhost/tallied
FINANCE_SECRET_KEY=${SECRET_KEY}
FINANCE_DEV_MODE=true
FINANCE_DEV_USER_EMAIL=claudius@tallied.dev
FINANCE_DEV_USER_PASSWORD=demo123
FINANCE_BASE_URL=http://localhost:8000
EOF
  green "[setup] backend/.env created (dev mode enabled)"
else
  green "[setup] backend/.env already exists — skipping"
fi

# ── 2. Python virtual environment + dependencies ────────────────────────────
if [ ! -d backend/.venv ]; then
  yellow "[setup] Creating Python virtual environment..."
  if command -v uv &>/dev/null; then
    uv venv backend/.venv --python python3
    uv pip install -r backend/requirements.txt --python backend/.venv/bin/python
  else
    python3 -m venv backend/.venv
    backend/.venv/bin/pip install --upgrade pip -q
    backend/.venv/bin/pip install -r backend/requirements.txt -q
  fi
  green "[setup] Backend dependencies installed"
else
  green "[setup] backend/.venv already exists — skipping"
fi

# ── 3. Frontend dependencies ────────────────────────────────────────────────
if [ ! -d frontend/node_modules ]; then
  yellow "[setup] Installing frontend dependencies..."
  (cd frontend && npm install --no-audit --no-fund --loglevel=error --legacy-peer-deps)
  green "[setup] Frontend dependencies installed"
else
  green "[setup] frontend/node_modules already exists — skipping"
fi

# ── 4. Docker daemon (start if installed but not running) ───────────────────
if command -v docker &>/dev/null && ! docker info &>/dev/null 2>&1; then
  yellow "[setup] Docker installed but daemon not running — starting dockerd..."
  dockerd &>/var/log/dockerd.log &
  for i in $(seq 1 15); do
    if docker info &>/dev/null 2>&1; then
      green "[setup] Docker daemon started"
      break
    fi
    sleep 1
    if [ "$i" -eq 15 ]; then
      yellow "[setup] Could not start Docker daemon"
    fi
  done
fi

# ── 5. PostgreSQL via Docker Compose ────────────────────────────────────────
if ! command -v docker &>/dev/null || ! docker info &>/dev/null 2>&1; then
  yellow "[setup] Docker not available — skipping PostgreSQL, migrations, and seed"
  yellow "[setup] Backend tests use SQLite (no Docker needed)"
elif docker compose ps postgres 2>/dev/null | grep -q "running"; then
  green "[setup] PostgreSQL already running — skipping"
  DB_READY=true
else
  yellow "[setup] Starting PostgreSQL..."
  docker compose up -d postgres
  echo -n "[setup] Waiting for Postgres..."
  DB_READY=false
  for i in $(seq 1 30); do
    if docker compose exec postgres pg_isready -U tallied &>/dev/null; then
      echo ""
      green "[setup] PostgreSQL is ready on localhost:5432"
      DB_READY=true
      break
    fi
    echo -n "."
    sleep 1
    if [ "$i" -eq 30 ]; then
      echo ""
      red "[setup] WARNING: PostgreSQL did not become ready in 30s"
    fi
  done
fi

# ── 6. Run Alembic migrations (only if DB is available) ─────────────────────
if [ "${DB_READY:-false}" = "true" ]; then
  yellow "[setup] Running database migrations..."
  (cd backend && source .venv/bin/activate && PYTHONPATH=. alembic upgrade head 2>/dev/null) && \
    green "[setup] Migrations applied" || \
    yellow "[setup] Migrations skipped (may need manual attention)"

  # ── 7. Seed test data ────────────────────────────────────────────────────
  yellow "[setup] Seeding test data (Claudius Banks)..."
  (cd backend && source .venv/bin/activate && PYTHONPATH=. python ../scripts/seed_test_data.py --reset 2>/dev/null) && \
    green "[setup] Test data seeded" || \
    yellow "[setup] Seed skipped (may need manual attention)"
fi

# ── Done ────────────────────────────────────────────────────────────────────
green ""
green "========================================="
green "  Tallied environment ready!"
green "  Run 'make dev' to start dev servers"
green "========================================="
